#!/bin/bash

# Script to delete existing data, create an index with deduplication enabled, and add 20 popular movie documents

SERVER_URL="http://localhost:8080"
INDEX_NAME="imdb_movies"
DATA_DIR="./search_data" # The directory your Go app uses for persistence

echo "--------------------------------------------------------------------"
echo "IMPORTANT: This script will DELETE the directory: $DATA_DIR"
echo "This is to ensure a fresh start for the search index."
echo "Press Enter to continue, or Ctrl+C to cancel."
echo "--------------------------------------------------------------------"
read -r


if [ -d "$DATA_DIR" ]; then
    echo "Deleting existing data directory: $DATA_DIR..."
    rm -rf "$DATA_DIR"
    if [ $? -eq 0 ]; then
        echo "Data directory deleted successfully."
    else
        echo "Error deleting data directory. Please check permissions."
        exit 1
    fi
else
    echo "Data directory $DATA_DIR does not exist. No need to delete."
fi

# It's good practice to wait a brief moment to ensure the Go application
# (if it was running and watching the directory) has time to recognize the change,
# or ideally, restart the Go application after running this script's deletion part.
# For this script, we assume you'll run this, then run the Go app, or the Go app handles
# directory disappearance gracefully on its own (which it should with os.MkdirAll).

echo -e "\nAttempting to create index: $INDEX_NAME..."
echo "Ensure your Go search engine application is running at $SERVER_URL"
echo "(If you deleted data while it was running, you might need to restart it for a clean load)"


# 1. Create the index
curl -s -X POST -H "Content-Type: application/json" -d '{
    "name": "'"$INDEX_NAME"'",
    "searchable_fields": ["title", "cast", "crew", "genres", "tags"],
    "filterable_fields": ["genres", "release_date", "popularity", "type", "cast"],
    "distinct_field": "uuid",
    "ranking_criteria": [
        {"field": "popularity", "order": "desc"},
        {"field": "release_date", "order": "desc"}
    ],
    "min_word_size_for_1_typo": 4,
    "min_word_size_for_2_typos": 7,
    "fields_without_prefix_search": ["tags"]
}' "$SERVER_URL/indexes" | jq .
# If you don't have jq, use:
# }' "$SERVER_URL/indexes"; echo ""


echo -e "\nAttempting to add 20 movie documents to index: $INDEX_NAME..."

# 2. Add 20 movie documents
# Note: UUIDs will be auto-generated by the server as they are omitted here.
curl -s -X PUT -H "Content-Type: application/json" -d '[
  {
    "title": "The Shawshank Redemption",
    "type": "movie",
    "cast": ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    "crew": ["director:Frank Darabont", "writer:Stephen King"],
    "genres": ["Drama"],
    "tags": ["prison", "hope", "friendship", "wrongful imprisonment"],
    "release_date": "1994-09-23T00:00:00Z",
    "popularity": 9.3
  },
  {
    "title": "The Godfather",
    "type": "movie",
    "cast": ["Marlon Brando", "Al Pacino", "James Caan"],
    "crew": ["director:Francis Ford Coppola", "writer:Mario Puzo"],
    "genres": ["Crime", "Drama"],
    "tags": ["mafia", "family", "power", "classic"],
    "release_date": "1972-03-24T00:00:00Z",
    "popularity": 9.2
  },
  {
    "title": "The Dark Knight",
    "type": "movie",
    "cast": ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    "crew": ["director:Christopher Nolan", "writer:Jonathan Nolan"],
    "genres": ["Action", "Crime", "Drama"],
    "tags": ["superhero", "batman", "joker", "moral conflict"],
    "release_date": "2008-07-18T00:00:00Z",
    "popularity": 9.0
  },
  {
    "title": "Pulp Fiction",
    "type": "movie",
    "cast": ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    "crew": ["director:Quentin Tarantino", "writer:Quentin Tarantino"],
    "genres": ["Crime", "Drama"],
    "tags": ["non-linear", "cult classic", "gangster", "dialogue"],
    "release_date": "1994-10-14T00:00:00Z",
    "popularity": 8.9
  },
  {
    "title": "Schindler''''s List",
    "type": "movie",
    "cast": ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes"],
    "crew": ["director:Steven Spielberg", "writer:Thomas Keneally"],
    "genres": ["Biography", "Drama", "History"],
    "tags": ["holocaust", "WWII", "rescue", "based on true story"],
    "release_date": "1993-12-15T00:00:00Z",
    "popularity": 8.9
  },
  {
    "title": "The Lord of the Rings: The Return of the King",
    "type": "movie",
    "cast": ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"],
    "crew": ["director:Peter Jackson", "writer:J.R.R. Tolkien"],
    "genres": ["Action", "Adventure", "Drama", "Fantasy"],
    "tags": ["epic", "fantasy", "middle-earth", "final battle"],
    "release_date": "2003-12-17T00:00:00Z",
    "popularity": 8.9
  },
  {
    "title": "Forrest Gump",
    "type": "movie",
    "cast": ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    "crew": ["director:Robert Zemeckis", "writer:Winston Groom"],
    "genres": ["Drama", "Romance"],
    "tags": ["life story", "americana", "historical events", "uplifting"],
    "release_date": "1994-07-06T00:00:00Z",
    "popularity": 8.8
  },
  {
    "title": "Fight Club",
    "type": "movie",
    "cast": ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    "crew": ["director:David Fincher", "writer:Chuck Palahniuk"],
    "genres": ["Drama"],
    "tags": ["anti-consumerism", "anarchy", "psychological", "twist ending"],
    "release_date": "1999-10-15T00:00:00Z",
    "popularity": 8.8
  },
  {
    "title": "Inception",
    "type": "movie",
    "cast": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    "crew": ["director:Christopher Nolan", "writer:Christopher Nolan"],
    "genres": ["Action", "Adventure", "Sci-Fi"],
    "tags": ["dreams", "heist", "mind-bending", "complex plot"],
    "release_date": "2010-07-16T00:00:00Z",
    "popularity": 8.8
  },
  {
    "title": "The Matrix",
    "type": "movie",
    "cast": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    "crew": ["director:Lana Wachowski", "director:Lilly Wachowski", "writer:Lana Wachowski"],
    "genres": ["Action", "Sci-Fi"],
    "tags": ["virtual reality", "dystopian", "cyberpunk", "chosen one"],
    "release_date": "1999-03-31T00:00:00Z",
    "popularity": 8.7
  },
  {
    "title": "Goodfellas",
    "type": "movie",
    "cast": ["Robert De Niro", "Ray Liotta", "Joe Pesci"],
    "crew": ["director:Martin Scorsese", "writer:Nicholas Pileggi"],
    "genres": ["Biography", "Crime", "Drama"],
    "tags": ["mafia", "gangster", "rise and fall", "based on true story"],
    "release_date": "1990-09-19T00:00:00Z",
    "popularity": 8.7
  },
  {
    "title": "Star Wars: Episode V - The Empire Strikes Back",
    "type": "movie",
    "cast": ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    "crew": ["director:Irvin Kershner", "writer:Leigh Brackett"],
    "genres": ["Action", "Adventure", "Fantasy", "Sci-Fi"],
    "tags": ["space opera", "classic", "star wars", "iconic twist"],
    "release_date": "1980-05-21T00:00:00Z",
    "popularity": 8.7
  },
  {
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "type": "movie",
    "cast": ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
    "crew": ["director:Peter Jackson", "writer:J.R.R. Tolkien"],
    "genres": ["Action", "Adventure", "Drama", "Fantasy"],
    "tags": ["epic", "fantasy", "middle-earth", "journey begins"],
    "release_date": "2001-12-19T00:00:00Z",
    "popularity": 8.8
  },
  {
    "title": "One Flew Over the Cuckoo''''s Nest",
    "type": "movie",
    "cast": ["Jack Nicholson", "Louise Fletcher", "Danny DeVito"],
    "crew": ["director:Milos Forman", "writer:Ken Kesey"],
    "genres": ["Drama"],
    "tags": ["mental institution", "rebellion", "authority", "classic"],
    "release_date": "1975-11-19T00:00:00Z",
    "popularity": 8.7
  },
  {
    "title": "Seven Samurai",
    "type": "movie",
    "cast": ["Toshiro Mifune", "Takashi Shimura", "Keiko Tsushima"],
    "crew": ["director:Akira Kurosawa", "writer:Akira Kurosawa"],
    "genres": ["Action", "Adventure", "Drama"],
    "tags": ["samurai", "classic", "japanese cinema", "influential"],
    "release_date": "1954-04-26T00:00:00Z",
    "popularity": 8.6
  },
  {
    "title": "Se7en",
    "type": "movie",
    "cast": ["Morgan Freeman", "Brad Pitt", "Kevin Spacey"],
    "crew": ["director:David Fincher", "writer:Andrew Kevin Walker"],
    "genres": ["Crime", "Drama", "Mystery", "Thriller"],
    "tags": ["serial killer", "dark", "detective", "seven deadly sins"],
    "release_date": "1995-09-22T00:00:00Z",
    "popularity": 8.6
  },
  {
    "title": "The Silence of the Lambs",
    "type": "movie",
    "cast": ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
    "crew": ["director:Jonathan Demme", "writer:Thomas Harris"],
    "genres": ["Crime", "Drama", "Thriller"],
    "tags": ["fbi", "serial killer", "psychological", "hannibal lecter"],
    "release_date": "1991-02-14T00:00:00Z",
    "popularity": 8.6
  },
  {
    "title": "City of God",
    "type": "movie",
    "cast": ["Alexandre Rodrigues", "Leandro Firmino", "Phellipe Haagensen"],
    "crew": ["director:Fernando Meirelles", "director:Kátia Lund", "writer:Paulo Lins"],
    "genres": ["Crime", "Drama"],
    "tags": ["favela", "brazil", "gangs", "coming-of-age"],
    "release_date": "2002-08-30T00:00:00Z",
    "popularity": 8.6
  },
  {
    "title": "Saving Private Ryan",
    "type": "movie",
    "cast": ["Tom Hanks", "Matt Damon", "Tom Sizemore"],
    "crew": ["director:Steven Spielberg", "writer:Robert Rodat"],
    "genres": ["Drama", "War"],
    "tags": ["WWII", "D-Day", "realism", "squad"],
    "release_date": "1998-07-24T00:00:00Z",
    "popularity": 8.6
  },
  {
    "title": "Interstellar",
    "type": "movie",
    "cast": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    "crew": ["director:Christopher Nolan", "writer:Jonathan Nolan"],
    "genres": ["Adventure", "Drama", "Sci-Fi"],
    "tags": ["space travel", "dystopian future", "relativity", "family"],
    "release_date": "2014-11-07T00:00:00Z",
    "popularity": 8.6
  }
]' "$SERVER_URL/indexes/$INDEX_NAME/documents" | jq .
# If you don't have jq, use:
# ]' "$SERVER_URL/indexes/$INDEX_NAME/documents"; echo ""

echo -e "\nScript finished."
